### ISSUE TITLE
Design Doc

### ISSUE THREAD

**Issue by hohyon-ryu** [open-korean-text/open-korean-text-web#3]

**Comment by hohyon-ryu** [comment]
Design doc here: https://github.com/open-korean-text/open-korean-text-web/wiki/Design-Doc

**Comment by iamyoongdi** [comment]
![user_flow](https://cloud.githubusercontent.com/assets/21121466/24321136/512e5580-1188-11e7-9eb1-cbdae1a32236.jpg)

**Comment by hohyon-ryu** [comment]
Acutally, the input of extract phrase is a tokenized text. Extract phrases는 tokenize에서 화살표가 나와야 해요.

**Comment by hohyon-ryu** [comment]
다 동사구로 통일하는 게 좋을 것 같아요.

Tokenization / tokenize
Stemming / stem
Normalization / normalize

**Comment by iamyoongdi** [comment]
![user_flow_2](https://cloud.githubusercontent.com/assets/21121466/24323024/960d1428-11b2-11e7-9fe5-6c0e656b514f.jpg)

**Comment by hohyon-ryu** [comment]
베리나이스. Normalize 는 preprocess 같은 개념이라 tokenize 전 단계로 봐도 되고 지금처럼 같은 단계로 봐도 되요
